#!/bin/bash
#SBATCH --partition=common
#SBATCH --output=test_%A_%a.out
#SBATCH --error=test_%A_%a.err
#SBATCH --array=0-1

echo "SLURM_ARRAY_TASK_ID: $SLURM_ARRAY_TASK_ID"
echo "SLURM_ARRAY_JOB_ID : $SLURM_ARRAY_JOB_ID"
echo "SLURM_CPUS_ON_NODE : $SLURM_CPUS_ON_NODE"
echo "SLURM_CPUS_PER_TASK: $SLURM_CPUS_PER_TASK"
echo "SLURM_MEM_PER_CPU  : $SLURM_MEM_PER_CPU"
echo "SLURM_MEM_PER_NODE : $SLURM_MEM_PER_NODE"
echo "SLURM_NTASKS       : $SLURM_NTASKS"
echo "SLURMD_NODENAME    : $SLURMD_NODENAME"

